import Script from "next/script";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata = {
	title: "A Profile",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<body>
			<Header />
			{children}
			<Footer />
		</body>
	);
}
