import Script from "next/script";

import Footer from "@/components/Footer";

export const metadata = {
	title: "A Profile",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<body>
			{children}
			<Footer />
			<Script src="/assets/js/feather.min.js" />
		</body>
	);
}
