import Script from "next/script";
import Head from "next/head";
import Link from "next/link";

import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<Head>
				<meta charset="UTF-8" />
				<meta http-equiv="X-UA-Compatible" content="IE=edge" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />

				<Link rel="preconnect" href="https://fonts.googleapis.com" />
				<Link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<Link
					href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<body className="bg-gray-100">{children}</body>
			<Script src="/assets/js/feather.min.js" />
		</html>
	);
}
